### PR TITLE
Added Data_B10 Category and related enums

### PR DESCRIPTION
**Pull request by EasyG0ing1**
After creating issue #5 I decided to look at the code and see what it would take to get the library to do both kinds of data units so I added the Data_B10 Category and related enums and updated the README to include the addition.

### CODE REVIEW

**Comment by EasyG0ing1** [comment]
I also changed the way the BigNumbers are created for both Data Categories. It should technically be more accurate doing the calls this way when the class is instantiated.... decimal precision should be more accurate.

Edit: And I added TERABIT, PETABIT and PETABYTE

**Comment by EasyG0ing1** [comment]
@HanSolo If you'd prefer - I was looking over the Categories and thought maybe it would make more sense to just add these additional enums to the one DATA category but suffix them with something like `_BASE1000` or maybe just `_B1000` that way, still only need to instantiate with a single DATA category but then convert with either the default of 1024 or 1000 via `_B1000`

**Comment by EasyG0ing1** [comment]
Since that seemed to be more consistent with the rest of the library, I went back to a single Data category, then suffixed the 1000 based calculations with _B1000, added all currently known data unit definitions and corrected all of the labeling inconsistencies as well as update the README.

**Comment by HanSolo** [comment]
That was exactly the approach I would also have used... 👍🏻😁

**Pull request merged**
